#!/usr/bin/env bash
# Assemble PERFORMANCE.md from the committed bench data: every table comes
# straight from scripts/perf_analysis.py (no hand-transcribed numbers), wrapped
# in the prose. Regenerate after refreshing bench/ with scripts/bench_primitives.sh.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

PA="python3 scripts/perf_analysis.py"
M4=bench/primitives_hardy.md
M4_HEAVY_EXT=bench/heavy_extended_hardy.md
EPYC=bench/primitives_moore.md
PI=bench/primitives_darby.md
GCD_SCALE=bench/gcd_scaling_hardy.md
GMP_GCD_SCALE=bench/gmp_gcd_scaling_hardy.md
OUT=PERFORMANCE.md

# Regenerate the scaling SVGs too, so they never drift from the tables.
for fam in arithmetic division montgomery number-theory; do
    $PA plot "$fam" "assets/scaling-$fam.svg" "M4=$M4" "EPYC=$EPYC" "Pi=$PI" >/dev/null
done
# The variable-time figure carries the extended heavy-tail record (5120-8192
# bits) alongside the primitives sizes, so the curve runs as far as the
# extrema table it sits under.
$PA plot variable-time assets/scaling-variable-time.svg \
    "M4=$M4,$M4_HEAVY_EXT" "EPYC=$EPYC" "Pi=$PI" >/dev/null
$PA plot gcd-at-scale assets/scaling-gcd-at-scale.svg \
    "rump=$GCD_SCALE" "GMP=$GMP_GCD_SCALE" >/dev/null

{
cat <<'MD'
# PERFORMANCE

Per-primitive microbenchmarks of rump, driven by
[pilot-bench](https://github.com/darrelllong/pilot-bench) over random operands,
with a per-primitive comparison against GMP. Every number here is reproducible
with `scripts/bench_primitives.sh`; the tables and graphs are regenerated by
`scripts/perf_analysis.py` (and the whole document by `scripts/build_performance.sh`).

## Method

Each `pilot_mp <op>` invocation draws **one fresh random operand** (seeded
from the OS clock, so every trial is independent) and measures it as follows:
the operation is repeated until the accumulated elapsed time exceeds a 2 ms
calibration floor, and the reading is elapsed time divided by the repetition
count, which keeps timer-resolution and loop-overhead error below one part in
10⁴ of every reading. pilot-bench runs the program repeatedly until the
mean's 95 % confidence interval converges; its saved readings are then a
random sample of the primitive's cost over random inputs, from which we
report both:

- the **mean** — the average cost over random inputs, and
- the **extrema** — min / p50 / p99 / max and the `max/min` spread,
  which for a variable-time primitive is the data-dependent behaviour that a
  mean hides.

Two primitives are **heavy-tailed**. `is_probable_prime` on a random operand
is a mixture: roughly half of all draws are even and exit on the first trial
division; most odd composites fall to the 168-prime sieve within
microseconds; the ≈ 8 % that survive it (Mertens: ∏(1 − 1/p) over p ≤ 997 is
≈ 0.081) pay at least one full Miller–Rabin exponentiation — 2.8 ms at 2048
bits, 24 ms at 4096 — and a prime, at probability 1/ln 2ⁿ, pays all twelve
rounds. The mean is real and increases monotonically with size, but the tail
sets it, so a faithful estimate requires a sample of several hundred trials;
these two operations therefore receive a 120 s collection session where the
others receive 30 s. (An earlier revision of this table showed `isprime`
means *decreasing* past 2048 bits. That was a harness defect, not arithmetic:
the operand pool then generated a random prime at the operand size for every
operation, so each 4096-bit trial cost seconds of setup and the session
starved — too few trials to contain the 8 % tail. With the corrected pool the
means are monotone through 6144 bits — 217 µs, 1.41 ms, 5.06 ms, 11.5 ms at
2048, 4096, 5120, 6144 — with the tail present at every width;
`bench/isprime_extended_hardy.md` holds the verification rows.) `sqrt_mod` has the same structure — a non-residue
rejects after one Euler-criterion exponentiation, a modulus with
`p ≡ 3 (mod 4)` takes a single exponentiation, and a high 2-adic valuation
takes the full Tonelli–Shanks descent — plus one cost the harness cannot
avoid: each trial must generate a fresh random prime modulus, which at 4096
bits on the Pi dominates the session and leaves that cell's sample thin (its
confidence-interval column discloses this). For both operations the interval
converges slowly (means carry the `~` mark) and the extrema columns are the
primary result. The prime-conditioned rows (`isprime_true`, and `sqrt_mod`
throughout) carry one structural limit: every trial must first generate a
random prime of the row's width, which beyond ~4 kbit costs tens of seconds
per trial and bounds the session's trial count. On the M4, long trials also
showed scheduling-dependent timing variance under background execution that
short trials do not; conditioned cells whose samples did not meet the
standard are omitted there, and the EPYC and Pi rows — spreads of 1.01–1.27
across every width — carry the conditioned-cost result. The outcome-conditioned `isprime_true` row is the complement:
on a prime, the cost is the sieve plus exactly twelve Miller–Rabin rounds, a
tight distribution whose mean converges in a handful of trials — the mixture
row characterizes the distribution a random operand induces, the conditioned
row the cost a caller plans around. The extrema table extends both
heavy-tailed operations to 8192 bits in 1024-bit steps on the M4
(`bench/heavy_extended_hardy.md`): the isprime record that once reversed past
2048 bits now rises monotonically through every width.

Operation glossary (integer sizes are the operand bit width; field sizes are the
degree of GF(2^m)):

| op | what it measures |
|---|---|
| `add` `sub` `mul` `sqr` | schoolbook/Karatsuba/Toom arithmetic on two random operands |
| `divrem` `modulo` | Knuth Algorithm D division, full width by half width |
| `modmul` | one `mul` then a reduction, general (non-Montgomery) modulus |
| `montmul` `montsqr` | one Montgomery multiply / square, operands already in the domain |
| `montsetup` | building a `MontgomeryCtx` (the one division and R² setup) |
| `gcd` `gcdext` `modinv` `jacobi` | the number-theory family |
| `sqrtmod` | `sqrt_mod` — a modular square root by Tonelli–Shanks (several exponentiations) |
| `isprime` | `is_probable_prime` on a fully random operand — the outcome mixture; its extrema carry the variable-time signal, its p99 the one-round composite cost |
| `isprime_true` | `is_probable_prime` on a random prime of the row's width — the outcome-conditioned accept cost: the sieve plus all twelve Miller–Rabin rounds, the cost a caller plans around |
| `gf2m_*` | binary-field multiply / square / sqrt / pow / inverse |

Three further rows measure exponentiation under fixed workloads taken from
classical public-key cryptography. rump is a general-purpose multiprecision
library; these rows are grouped and labeled as the RSA- and DH-specific set
they are, and they exist for the measurement axes they pin down.

| op | workload | what it isolates |
|---|---|---|
| `montpow_e65537` | RSA verification: exponent fixed at 65537 = 2¹⁶+1 | the exponent floor — two set bits give sixteen squarings and one multiply, measuring kernel scaling with exponent work at its minimum |
| `montpow_rand` | finite-field DH/DSA: fresh random exponent of fixed 256-bit length | the realistic-exponent axis at constant length, so the size fit varies one variable |
| `modpow` | the same DH-shaped workload through the public `mod_pow` | dispatch overhead relative to `montpow_rand` (Montgomery ladder for odd moduli) |

Exponentiation cost is (exponent bits) × (kernel cost) and is linear in
exponent length, so every other length follows from these rows: a full-width
2048-bit exponent costs eight times the `montpow_rand` row.

All measurements are single-threaded, against GMP 6.3.0 on every host:

| label | machine | cores | memory | OS |
|---|---|---|---|---|
| **M4** | Apple M4 | 10 | 32 GiB | macOS 26.5.1 |
| **EPYC** | 2 × AMD EPYC 7452 (Zen 2) | 64 (128 threads) | 256 GiB | Ubuntu 24.04.4 LTS |
| **Pi** | Raspberry Pi 5 Model B Rev 1.1 (4 × Cortex-A76) | 4 | 8 GiB | Debian 13 |

GMP numbers come from `pilot_gmp`, a C mirror of `pilot_mp` driven through
the same pilot-bench harness: the same operand distribution, calibration
floor, convergence criterion, and session limits.

## Fitted complexity

Least-squares log–log fit of mean vs bit width, `mean ≈ c·n^α`; the table gives
the **exponent α** only. (The fit's intercept `c` is deliberately not shown: it
carries units of ns/bit^α — *not* nanoseconds — so it is neither a time nor
comparable across rows with different α. Read actual times from the cost tables
below, never α or `c` as a speed.) At 256–4096 bits (4–64 limbs) the exponents
are **sub-asymptotic**: fixed per-call overhead flattens the cheap ops (`add`
reads α≈0.3 though it is O(n)); a higher α means a steeper curve, so `mul`
(α≈1.8) overtakes `add` well before these sizes even though it starts cheaper.
The Euclid family now reads α≈1.0–1.1 — **Lehmer batching** cuts both the
constant and the observed growth against classical Euclid's ≈1.4. `mul`/`sqr`
read α≈1.8 because at these sizes they are mostly schoolbook with a single
Karatsuba split, still below the Toom crossover (~8192 bits). `sqrtmod` and
`isprime` are heavy-tailed: their means are monotone in size but tail-set,
so their fitted exponents move with the sample's composition — read their
extrema (see above).

MD

$PA fit "M4=$M4" "EPYC=$EPYC" "Pi=$PI"

cat <<'MD'

## Cost by method

MD

$PA means "M4=$M4" "EPYC=$EPYC" "Pi=$PI"

cat <<'MD'

EPYC runs ~1.3–1.8× behind the M4 across the board (lower single-thread clock),
and the Pi ~2–5× behind it (a small board core) — the same shapes, shifted up.
The scaling graphs plot all three.

![arithmetic scaling](assets/scaling-arithmetic.svg)

![division scaling](assets/scaling-division.svg)

![montgomery scaling](assets/scaling-montgomery.svg)

![number theory scaling](assets/scaling-number-theory.svg)

## Versus GMP

Each cell is rump time / GMP time / ratio. Lower ratio is better; **1.0×** would
mean parity. `isprime` is omitted here — its heavy-tailed mean makes the ratio
meaningless (see Extrema). rump's Montgomery domain, `sqrt_mod`, and GF(2^m)
have no `mpz` counterpart and so cannot appear in the comparison; their costs
are in the tables above.

### M4

MD

$PA compare "$M4" bench/gmp_hardy.md | grep -v '`isprime`'

cat <<'MD'

### EPYC

MD

$PA compare "$EPYC" bench/gmp_moore.md | grep -v '`isprime`'

cat <<'MD'

### Pi

MD

$PA compare "$PI" bench/gmp_darby.md | grep -v '`isprime`'

cat <<'MD'

### Interpretation

The comparison sorts rump's primitives into groups, and the grouping is by
**algorithm**, not by language:

- **Competitive — matched algorithm.** `modpow` is 1.1–3.4× off GMP because both
  use windowed Montgomery exponentiation; the gap is constant factors (GMP's
  assembly `mulx`/`adcx` inner loop). `divrem` and `modmul` sit at ~2–4× for the
  same reason. Notably this tightens on the **Pi** (`mul` 1.3–1.9×, `modpow`
  1.1–1.6×): GMP's hand-tuned assembly edge is a wide-core advantage that shrinks
  on the Pi's simpler pipeline, where the pure-Rust penalty is smallest.

- **The Euclid family: Lehmer's algorithm replaced classical Euclid, and
  binary reciprocity replaced the division-per-step Jacobi.** `gcd`,
  `gcd_extended`, and `mod_inverse` ran classical Euclid — one full
  multiprecision division per quotient — and stood 17–89× behind GMP; on
  Lehmer's algorithm they stand 4–13×. `jacobi` performed a full division per
  reduction step and stood 12–29× behind; on binary reciprocity it stands
  2–12×. At 256–4096 bits all four engines are O(n²) while GMP runs
  subquadratic **Half-GCD (HGCD)** under each, so the ratios rise with size on
  the wide M4/EPYC cores. Above its crossover each of the four dispatches to
  a Half-GCD of its own — `gcd` and `jacobi` at ~131 kbit, `gcd_extended`
  and `mod_inverse` at ~32 kbit (see *GCD at scale* below). (On the Pi the ratios narrow
  with size instead — from ~10–12× at 256 bits to ~4× at 4096 — as rump's
  fixed per-call overhead amortizes.)

- **`mul`/`sqr` — 1.3–7.5×, widening on the wide cores.** rump climbs
  schoolbook → Karatsuba → **Toom-3 → Toom-4**; Toom-3 crosses in above ~8192
  bits, so at crypto sizes (≤4096 bits) rump is on Karatsuba and the gap is GMP's
  assembly base-case, not the algorithm. GMP escalates to Toom-6.5/8.5 → FFT far
  above rump's range.

- **`add`/`sub` — 1.2–4.5×, formerly 2–15×.** Both pilots now measure the
  same shape: the result written into long-lived storage (GMP's
  `mpz_add(r, a, b)` into a reused `r`; rump's three-operand `assign_add` /
  `assign_sub` into a reused buffer — one carry or borrow pass, no
  allocation once the buffer is settled). What remains is code generation:
  rump's carry chain is portable Rust over `u128` accumulators where GMP's
  is assembly `adc`/`sbc`. The band is nearly host-independent — M4
  1.2–4.5×, EPYC 1.3–3.9×, Pi 1.2–4.0× — tightest at 256 bits, where call
  overhead dominates both sides, and widening with operand length as the
  carry chains dominate. The absolute differences run from under a
  nanosecond (M4 `sub` at 256 bits) to ~130 ns (Pi at 4096).

- **Operations with no `mpz` counterpart.** The public Montgomery domain
  (`mul_mont`, `square_mont`, `pow`), `sqrt_mod`, and the GF(2^m) field
  operations cannot appear in this comparison because GMP's integer layer does
  not provide them; their costs are in the tables above.

### Completed and remaining algorithmic work

Completed to date: double-digit Lehmer for the Euclid family (17–89× behind
GMP reduced to 4–13× at 256–4096 bits), the division-free binary Jacobi
(12–29× reduced to 2–12×), Toom-3 and Toom-4 multiplication, Half-GCD behind
`gcd` (subquadratic above ~131 kbit), Half-GCD behind `gcd_extended` and
`mod_inverse` (above ~32 kbit), the Lehmer-batched Jacobi carrying
Möller's symbol state (above ~4 kbit; 181× at 1 Mbit reduced to 41×), and
the Half-GCD-threaded Jacobi (above ~131 kbit) — the symbol state carried
through the recursion, whose every applied quotient materializes in a
Lehmer batch or a guarded division, taking the symbol to O(M(n)·log n) and
the 1 Mbit ratio from 41× to 11.9×, where the symbol costs what `gcd`
costs (published treatment: Brent and Zimmermann, *An O(M(n) log n)
algorithm for the Jacobi symbol*, ANTS-IX, 2010; the threading design is
Möller's, GMP's `mpn_hgcd_jacobi`), and in-place `add`/`sub` — the signed
type's `add_assign_ref`/`sub_assign_ref` reusing the magnitude's buffer in
every sign combination, the unsigned type's three-operand
`assign_add`/`assign_sub` writing into caller-held storage, and a
buffer-reusing `Clone::clone_from` — which moved the cheapest operations'
ratios from 2–15× to 1.2–4.5× (the `add`/`sub` bullet above). The section
below measures the family at scale.

This closes the backlog of rump-against-GMP ratio work: in the primitive
comparison above, what still separates the columns is constant factors —
GMP's assembly base cases, Toom against FFT — not algorithms. Measured work
inside rump itself remains on the approved queue (ROADMAP.md): Cipolla's
square root, aimed at `sqrt_mod`'s 2-adic heavy tail in the extrema section
below, and Montgomery's batch inversion.

## GCD at scale

The tables above stop at 4096 bits, where the whole family runs its Lehmer
(or binary) engine. Above that, every one of the four changes algorithm.
`gcd` dispatches to **Half-GCD (HGCD)** past ~131 kbit (2048 limbs): Möller,
*On Schönhage's algorithm and subquadratic integer gcd computation*, Math.
Comp. 77 (2008), 589–607 — the algorithm behind GMP's `mpn_hgcd` — computing
the reduction matrix from the operands' top halves by recursion and replacing
Lehmer's O(n²) with O(M(n)·log n). `gcd_extended` and `mod_inverse` ride the
same driver with the transform accumulated, and their crossover is lower,
~32 kbit (512 limbs), because Lehmer's extended form carries full-width
signed cofactors through every batch while the driver folds that work into
one matrix accumulation per round. `jacobi` dispatches twice: at ~4 kbit
(64 limbs) from the binary algorithm to a Lehmer-batched quotient sequence,
Möller's five-bit symbol state replaying each batch's applied quotients, and
at ~131 kbit (2048 limbs, the same crossover as `gcd`'s) the state threads
through the Half-GCD recursion itself — every quotient the recursion applies
materializes in a Lehmer batch or a guarded division, and the state consumes
each one — making the symbol O(M(n)·log n) end to end. This section measures
the family from 8 kbit to 1 Mbit on the M4:

- **All four curves bend.** Every fit lands well below the Lehmer engines'
  α ≈ 2 (the fit table below), and the fits understate the change: each
  curve's lower range still runs Lehmer, with the subquadratic regime
  beginning only at its dispatch size. `jacobi`'s α ≈ 1.44 is the family's
  shallowest for the same mixed-regime reason, read in the other direction:
  its Lehmer segment is the family's most expensive, so the drop at its
  crossover is the steepest.
- **The ratios to GMP grow slowly for the Half-GCD functions and
  quadratically for `jacobi`.** Across the sweep, `gcd` runs 4.1× → 12×,
  `mod_inverse` 8.3× → 16×, and `gcd_extended` 7.8× → 21×; the residual
  growth comes from the multiplication ladder underneath — GMP's HGCD
  multiplies by FFT at these sizes, rump's by Toom — plus Half-GCD's own
  constants. `jacobi` runs 13.4× at 8 kbit narrowing to 9.5× at 64 kbit on
  the batched engine; where the threaded recursion engages the ratio drops
  to 6.6× at 128 kbit and then tracks `gcd`'s own — 7.6×, 9.1×, 11.9× at
  256 kbit, 512 kbit, 1 Mbit, against `gcd`'s 7.5×, 9.0×, 12.0×.
- **The jacobi ratio decomposes into two measured factors.** GMP computes
  the symbol as a symbol-tracking variant of its subquadratic gcd and pays
  the same price for both: 39.49 ms against 39.02 ms for gcd at 1 Mbit.
  rump's original binary engine — whose per-step sign contributions read the
  current operands' low bits, information a leading-digits batch does not
  carry — reached 7.15 s at 1 Mbit, a ratio of 181× factoring as
  (7153 ÷ 470) × (470 ÷ 39.5) = 15.2 × 11.9: jacobi against rump's own gcd,
  times the documented Half-GCD and Toom-versus-FFT gap. Möller's five-bit
  symbol state removes the low-bits obstruction — Schönhage's identities
  need only the quotient mod 4 — and the Lehmer-batched engine built on it
  brings 1 Mbit to 1.62 s and the ratio to 41×, leaving a factor of 3.5
  against rump's own gcd — quadratic versus subquadratic. Threading the
  same state through the Half-GCD recursion removes it: 470.44 ms against
  `gcd`'s 470.12 ms at 1 Mbit, equal to within 0.1%. The symbol costs what
  gcd costs, exactly as GMP's equal timings predicted, and the ratio stands
  at 11.9× — the lowest in the family.
- **The GMP column states the standard:** α ≈ 1.5 across the whole family,
  achieved by running HGCD beneath every one of these operations — which
  this crate now does. What separates the columns is no longer the
  algorithm but its constants: Toom against FFT under the matrix work, and
  GMP's assembly base cases.

MD

$PA fit "rump=$GCD_SCALE" "GMP=$GMP_GCD_SCALE"

cat <<'MD'

Rows are bit widths; each cell is rump time / GMP time / ratio.

MD

$PA compare --by-size "$GCD_SCALE" "$GMP_GCD_SCALE"

cat <<'MD'

![gcd at scale](assets/scaling-gcd-at-scale.svg)

## Extrema — the variable-time signal

Ranked by `max/min` spread (M4). A spread near 1.0 is data-independent; a large
spread means the primitive's cost depends on its input, which is why rump is
explicitly variable-time and must not be used where timing may not leak secrets.

Two operations produce the large spreads:
- **`isprime`** ranges from a ~20 ns small-factor rejection to a full
  twelve-round Miller–Rabin pass on a prime — a spread past **500,000×** at
  2048 bits; the exact figure tracks how many primes the random sample
  contained.
- **`sqrt_mod`** varies with the prime's 2-adic structure — a Blum prime takes
  the `(p+1)/4` shortcut, an NTT-friendly prime the full descent (200–450×).
- Everything else — plain arithmetic, the Montgomery kernels, the Lehmer'd
  Euclid family, GF(2^m) — sits at **1.0–1.6×**: cost tracks operand width, which
  is public, not the operand values.

MD

EXTREMA_MERGED="$(mktemp)"
cat "$M4" "$M4_HEAVY_EXT" > "$EXTREMA_MERGED"
$PA extrema "M4=$EXTREMA_MERGED"
rm -f "$EXTREMA_MERGED"

cat <<'MD'

![variable-time scaling](assets/scaling-variable-time.svg)

## Reproduction

```sh
cargo build --release --bin pilot_mp
bash scripts/bench_gmp.sh                      # builds pilot_gmp (needs libgmp)

# rump column, and the GMP column through the same harness, per host:
PILOT_PRESET=normal bash scripts/bench_primitives.sh > bench/primitives_<host>.md
PILOT_MP_BIN=target/bench_gmp/pilot_gmp \
  PILOT_PRESET=normal bash scripts/bench_primitives.sh > bench/gmp_<host>.md

# the GCD-at-scale sweep (8 kbit – 1 Mbit):
bash scripts/bench_gcd_scaling.sh > bench/gcd_scaling_<host>.md
PILOT_MP_BIN=target/bench_gmp/pilot_gmp \
  bash scripts/bench_gcd_scaling.sh > bench/gmp_gcd_scaling_<host>.md

# assemble the whole document (tables, graphs, prose):
bash scripts/build_performance.sh

# or drive the pieces directly:
python3 scripts/perf_analysis.py fit     M4=… EPYC=… Pi=…
python3 scripts/perf_analysis.py means   M4=… EPYC=… Pi=…
python3 scripts/perf_analysis.py compare bench/primitives_<h>.md bench/gmp_<h>.md
python3 scripts/perf_analysis.py extrema M4=…
python3 scripts/perf_analysis.py plot    <family> assets/scaling-<family>.svg M4=… EPYC=… Pi=…
```
MD
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
