#!/usr/bin/env bash
# Assemble PERFORMANCE.md from the committed bench data: every table comes
# straight from scripts/perf_analysis.py (no hand-transcribed numbers), wrapped
# in the prose. Regenerate after refreshing bench/ with scripts/bench_primitives.sh.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

PA="python3 scripts/perf_analysis.py"
M4=bench/primitives_hardy.md
EPYC=bench/primitives_moore.md
PI=bench/primitives_darby.md
OUT=PERFORMANCE.md

# Regenerate the scaling SVGs too, so they never drift from the tables.
for fam in arithmetic division montgomery number-theory variable-time; do
    $PA plot "$fam" "assets/scaling-$fam.svg" "M4=$M4" "EPYC=$EPYC" "Pi=$PI" >/dev/null
done

{
cat <<'MD'
# PERFORMANCE

Per-primitive microbenchmarks of rump, driven by
[pilot-bench](https://github.com/darrelllong/pilot-bench) over random operands,
with a per-primitive comparison against GMP. Every number here is reproducible
with `scripts/bench_primitives.sh`; the tables and graphs are regenerated by
`scripts/perf_analysis.py` (and the whole document by `scripts/build_performance.sh`).

## Method

Each `pilot_mp <op>` invocation draws **one fresh random operand** (seeded from
the OS clock, so every trial is independent) and times the primitive with
enough inner repetitions to beat the clock. pilot-bench repeats the program
until the mean's 95 % confidence interval converges; its saved readings are
then a random sample of the primitive's cost, from which we report both:

- the **mean** — the average cost over random inputs, and
- the **extrema** — `min / p50 / p99 / max` ns/op and the `max/min` spread,
  which for a variable-time primitive is the data-dependent behaviour that a
  mean hides.

Two primitives are **heavy-tailed**, and for them the mean is not a meaningful
number at all. `is_probable_prime` costs either an instant trial-division
rejection (a random odd number almost always has a small factor, a few hundred
ns) or a full Miller–Rabin pass (tens of µs) when the sample happens to contain
an actual prime — so its mean is set by *how many primes the random draw hit*,
not by operand size, and it is **non-monotonic in size**: a size whose sample
hit no hard primes reads faster than a smaller one that did. `sqrt_mod`'s
Tonelli–Shanks cost swings with the prime's 2-adic structure (a non-residue
input rejects in µs; a Blum prime `p ≡ 3 (mod 4)` takes one exponentiation; a
`p ≡ 1 (mod 4)` of high 2-adic valuation takes the full descent). Their sample
variance never stabilises, so the mean CI cannot converge; means are marked
`~`, and **only their extrema are the meaningful result** — do not read their
means or fitted exponents as physics.

Operation glossary (integer sizes are the operand bit width; field sizes are the
degree of GF(2^m)):

| op | what it measures |
|---|---|
| `add` `sub` `mul` `sqr` | schoolbook/Karatsuba/Toom arithmetic on two random operands |
| `divrem` `modulo` | Knuth Algorithm D division, full width by half width |
| `modmul` | one `mul` then a reduction, general (non-Montgomery) modulus |
| `montmul` `montsqr` | one Montgomery multiply / square, operands already in the domain |
| `montsetup` | building a `MontgomeryCtx` (the one division and R² setup) |
| `montpow_e65537` | Montgomery exponentiation to the **fixed exponent 65537** (2¹⁶+1, the RSA public exponent F4) — an RSA verify/encrypt |
| `montpow_rand` | Montgomery exponentiation to a fresh **256-bit random** exponent — a private-key / Diffie–Hellman shape |
| `modpow` | `mod_pow` to a 256-bit random exponent (dispatches to the Montgomery ladder for odd moduli) |
| `gcd` `gcdext` `modinv` `jacobi` | the number-theory family |
| `sqrtmod` | `sqrt_mod` — a modular square root by Tonelli–Shanks (several exponentiations) |
| `isprime` | `is_probable_prime` — trial-division sieve then Miller–Rabin |
| `gf2m_*` | binary-field multiply / square / sqrt / pow / inverse |

Hosts: **M4** (Apple M4, macOS), **EPYC** (AMD EPYC 7452, Linux), and **Pi**
(Raspberry Pi 5, Cortex-A76, Debian) — two ARM cores at opposite ends (a wide
desktop-class core and a small board core) and one x86 server core. GMP numbers
come from `pilot_gmp`, a C mirror driven through the same pilot-bench harness,
so the comparison is apples-to-apples down to the measurement method.

## Fitted complexity

Least-squares log–log fit of mean vs bit width, `mean ≈ c·n^α`; the table gives
the **exponent α** only. (The fit's intercept `c` is deliberately not shown: it
carries units of ns/bit^α — *not* nanoseconds — so it is neither a time nor
comparable across rows with different α. Read actual times from the cost tables
below, never α or `c` as a speed.) At 256–4096 bits (4–64 limbs) the exponents
are **sub-asymptotic**: fixed per-call overhead flattens the cheap ops (`add`
reads α≈0.3 though it is O(n)); a higher α means a steeper curve, so `mul`
(α≈1.8) overtakes `add` well before these sizes even though it starts cheaper.
The Euclid family now reads α≈1.0–1.1 — **Lehmer batching** cuts both the
constant and the observed growth against classical Euclid's ≈1.4. `mul`/`sqr`
read α≈1.8 because at these sizes they are mostly schoolbook with a single
Karatsuba split, still below the Toom crossover (~8192 bits). `sqrtmod` and
`isprime` are heavy-tailed; their fits are meaningless (see above).

MD

$PA fit "M4=$M4" "EPYC=$EPYC" "Pi=$PI"

cat <<'MD'

## Cost by method

MD

$PA means "M4=$M4" "EPYC=$EPYC" "Pi=$PI"

cat <<'MD'

EPYC runs ~1.3–1.8× behind the M4 across the board (lower single-thread clock),
and the Pi ~2–5× behind it (a small board core) — the same shapes, shifted up.
The scaling graphs plot all three.

![arithmetic scaling](assets/scaling-arithmetic.svg)

![division scaling](assets/scaling-division.svg)

![montgomery scaling](assets/scaling-montgomery.svg)

![number theory scaling](assets/scaling-number-theory.svg)

## Versus GMP

Each cell is `rump ns / gmp ns / ratio`. Lower ratio is better; **1.0×** would
mean parity. `isprime` is omitted here — its heavy-tailed mean makes the ratio
meaningless (see Extrema). rump's Montgomery domain, `sqrt_mod`, and GF(2^m)
have **no `mpz` counterpart** and so cannot appear: that absence is itself
rump's surplus over GMP's integer layer.

### M4

MD

$PA compare "$M4" bench/gmp_hardy.md | grep -v '`isprime`'

cat <<'MD'

### EPYC

MD

$PA compare "$EPYC" bench/gmp_moore.md | grep -v '`isprime`'

cat <<'MD'

### Pi

MD

$PA compare "$PI" bench/gmp_darby.md | grep -v '`isprime`'

cat <<'MD'

### Reading the gap

The comparison sorts rump's primitives into groups, and the grouping is by
**algorithm**, not by language:

- **Competitive — matched algorithm.** `modpow` is 1.1–3.4× off GMP because both
  use windowed Montgomery exponentiation; the gap is constant factors (GMP's
  assembly `mulx`/`adcx` inner loop). `divrem` and `modmul` sit at ~2–4× for the
  same reason. Notably this tightens on the **Pi** (`mul` 1.3–1.9×, `modpow`
  1.1–1.6×): GMP's hand-tuned assembly edge is a wide-core advantage that shrinks
  on the Pi's simpler pipeline, where the pure-Rust penalty is smallest.

- **Constant factor behind — was a *worse* algorithm, now fixed.** `gcd`,
  `gcd_extended`, and `mod_inverse` used to run **17–89×** slower on classical
  Euclid; they now run **4–13×** after the switch to **double-digit Lehmer**.
  `jacobi`, which did a full division per step, now runs **2–12×** on a
  **division-free binary reciprocity** (it was 12–29×). All four remain O(n²), so
  on the wide M4/EPYC cores the ratio still creeps up with size — GMP's
  **Half-GCD** is subquadratic. (On the Pi the Euclid ratios *narrow* with size,
  from ~10–12× at 256-bit to ~4× at 4096-bit, as rump's fixed per-call overhead
  amortizes.)

- **`mul`/`sqr` — 1.3–7.5×, widening on the wide cores.** rump climbs
  schoolbook → Karatsuba → **Toom-3 → Toom-4**; Toom-3 crosses in above ~8192
  bits, so at crypto sizes (≤4096 bits) rump is on Karatsuba and the gap is GMP's
  assembly base-case, not the algorithm. GMP escalates to Toom-6.5/8.5 → FFT far
  above rump's range.

- **`add`/`sub` — 2–15×, but nanoseconds.** Almost all of this is rump allocating
  a fresh `Vec` per call against GMP's in-place `mpn`; the absolute cost is tens
  of nanoseconds.

- **No contest — rump has it, `mpz` doesn't.** A public Montgomery domain
  (`mul_mont`/`pow`), modular square roots (`sqrt_mod`), and GF(2^m) fields.

### Where to work harder

Landed this round: **double-digit Lehmer** (`gcd`/`gcd_extended`/`mod_inverse`,
17–89× → 4–13×), **division-free binary Jacobi** (12–29× → 2–12×), and
**Toom-3/Toom-4** multiplication. What remains, biggest first:

1. **Half-GCD** for the Euclid family. Lehmer (done) cut the constant but the
   algorithm is still O(n²), so the residual gap grows with size on wide cores.
   HGCD recurses on the top half of the operands for O(M(n)·log n), with Lehmer
   as its base case — it is the one remaining algorithmic step for `gcd`,
   `gcdext`, and `modinv`.
2. **Jacobi through an HGCD that tracks the symbol.** `jacobi` is a binary O(n²)
   whose ratio widens to ~12×; batching its reduction the way Lehmer batches
   gcd, while carrying the reciprocity sign, closes it.
3. **In-place `add`/`sub`** (the 2–15× on the cheapest ops). A fresh `Vec` per
   call against GMP's in-place `mpn`; the absolute cost is nanoseconds, so last.

## Extrema — the variable-time signal

Ranked by `max/min` spread (M4). A spread near 1.0 is data-independent; a large
spread means the primitive's cost depends on its input, which is why rump is
explicitly variable-time and must not be used where timing may not leak secrets.

The two extremes tell the story:
- **`isprime`** ranges from an ~20 ns small-factor rejection to a full
  Miller–Rabin pass on a prime — a spread past **40,000×** at 2048-bit (the exact
  figure is data-dependent: it tracks how many hard primes the random sample hit).
- **`sqrt_mod`** varies with the prime's 2-adic structure — a Blum prime takes
  the `(p+1)/4` shortcut, an NTT-friendly prime the full descent (200–450×).
- Everything else — plain arithmetic, the Montgomery kernels, the Lehmer'd
  Euclid family, GF(2^m) — sits at **1.0–1.6×**: cost tracks operand width, which
  is public, not the operand values.

MD

$PA extrema "M4=$M4" | head -42

cat <<'MD'

The remaining 46 primitives all sit at **1.0–1.2×** — data-independent, their
cost set by operand width alone.

![variable-time scaling](assets/scaling-variable-time.svg)

## Reproduce

```sh
cargo build --release --bin pilot_mp
bash scripts/bench_gmp.sh                      # builds pilot_gmp (needs libgmp)

# rump column, and the GMP column through the same harness, per host:
PILOT_PRESET=normal bash scripts/bench_primitives.sh > bench/primitives_<host>.md
PILOT_MP_BIN=target/bench_gmp/pilot_gmp \
  PILOT_PRESET=normal bash scripts/bench_primitives.sh > bench/gmp_<host>.md

# assemble the whole document (tables, graphs, prose):
bash scripts/build_performance.sh

# or drive the pieces directly:
python3 scripts/perf_analysis.py fit     M4=… EPYC=… Pi=…
python3 scripts/perf_analysis.py means   M4=… EPYC=… Pi=…
python3 scripts/perf_analysis.py compare bench/primitives_<h>.md bench/gmp_<h>.md
python3 scripts/perf_analysis.py extrema M4=…
python3 scripts/perf_analysis.py plot    <family> assets/scaling-<family>.svg M4=… EPYC=… Pi=…
```
MD
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
