#!/usr/bin/env bash
# Assemble PERFORMANCE.md from the committed bench data: every table comes
# straight from scripts/perf_analysis.py (no hand-transcribed numbers), wrapped
# in the prose. Regenerate after refreshing bench/ with scripts/bench_primitives.sh.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

PA="python3 scripts/perf_analysis.py"
M4=bench/primitives_hardy.md
EPYC=bench/primitives_moore.md
PI=bench/primitives_darby.md
GCD_SCALE=bench/gcd_scaling_hardy.md
GMP_GCD_SCALE=bench/gmp_gcd_scaling_hardy.md
OUT=PERFORMANCE.md

# Regenerate the scaling SVGs too, so they never drift from the tables.
for fam in arithmetic division montgomery number-theory variable-time; do
    $PA plot "$fam" "assets/scaling-$fam.svg" "M4=$M4" "EPYC=$EPYC" "Pi=$PI" >/dev/null
done
$PA plot gcd-at-scale assets/scaling-gcd-at-scale.svg \
    "rump=$GCD_SCALE" "GMP=$GMP_GCD_SCALE" >/dev/null

{
cat <<'MD'
# PERFORMANCE

Per-primitive microbenchmarks of rump, driven by
[pilot-bench](https://github.com/darrelllong/pilot-bench) over random operands,
with a per-primitive comparison against GMP. Every number here is reproducible
with `scripts/bench_primitives.sh`; the tables and graphs are regenerated by
`scripts/perf_analysis.py` (and the whole document by `scripts/build_performance.sh`).

## Method

Each `pilot_mp <op>` invocation draws **one fresh random operand** (seeded
from the OS clock, so every trial is independent) and measures it as follows:
the operation is repeated until the accumulated elapsed time exceeds a 2 ms
calibration floor, and the reading is elapsed time divided by the repetition
count, which keeps timer-resolution and loop-overhead error below one part in
10⁴ of every reading. pilot-bench runs the program repeatedly until the
mean's 95 % confidence interval converges; its saved readings are then a
random sample of the primitive's cost over random inputs, from which we
report both:

- the **mean** — the average cost over random inputs, and
- the **extrema** — `min / p50 / p99 / max` ns/op and the `max/min` spread,
  which for a variable-time primitive is the data-dependent behaviour that a
  mean hides.

Two primitives are **heavy-tailed**. `is_probable_prime` on a random operand
is a mixture: roughly half of all draws are even and exit on the first trial
division; most odd composites fall to the 168-prime sieve within
microseconds; the ≈ 8 % that survive it (Mertens: ∏(1 − 1/p) over p ≤ 997 is
≈ 0.081) pay at least one full Miller–Rabin exponentiation — 2.8 ms at 2048
bits, 24 ms at 4096 — and a prime, at probability 1/ln 2ⁿ, pays all twelve
rounds. The mean is real and increases monotonically with size, but the tail
sets it, so a faithful estimate requires a sample of several hundred trials;
these two operations therefore receive a 120 s collection session where the
others receive 30 s. `sqrt_mod` has the same structure — a non-residue
rejects after one Euler-criterion exponentiation, a modulus with
`p ≡ 3 (mod 4)` takes a single exponentiation, and a high 2-adic valuation
takes the full Tonelli–Shanks descent — plus one cost the harness cannot
avoid: each trial must generate a fresh random prime modulus, which at 4096
bits on the Pi dominates the session and leaves that cell's sample thin (its
confidence-interval column discloses this). For both operations the interval
converges slowly (means carry the `~` mark) and the extrema columns are the
primary result.

Operation glossary (integer sizes are the operand bit width; field sizes are the
degree of GF(2^m)):

| op | what it measures |
|---|---|
| `add` `sub` `mul` `sqr` | schoolbook/Karatsuba/Toom arithmetic on two random operands |
| `divrem` `modulo` | Knuth Algorithm D division, full width by half width |
| `modmul` | one `mul` then a reduction, general (non-Montgomery) modulus |
| `montmul` `montsqr` | one Montgomery multiply / square, operands already in the domain |
| `montsetup` | building a `MontgomeryCtx` (the one division and R² setup) |
| `gcd` `gcdext` `modinv` `jacobi` | the number-theory family |
| `sqrtmod` | `sqrt_mod` — a modular square root by Tonelli–Shanks (several exponentiations) |
| `isprime` | `is_probable_prime` — trial-division sieve then Miller–Rabin |
| `gf2m_*` | binary-field multiply / square / sqrt / pow / inverse |

Three further rows measure exponentiation under fixed workloads taken from
classical public-key cryptography. rump is a general-purpose multiprecision
library; these rows are grouped and labeled as the RSA- and DH-specific set
they are, and they exist for the measurement axes they pin down.

| op | workload | what it isolates |
|---|---|---|
| `montpow_e65537` | RSA verification: exponent fixed at 65537 = 2¹⁶+1 | the exponent floor — two set bits give sixteen squarings and one multiply, measuring kernel scaling with exponent work at its minimum |
| `montpow_rand` | finite-field DH/DSA: fresh random exponent of fixed 256-bit length | the realistic-exponent axis at constant length, so the size fit varies one variable |
| `modpow` | the same DH-shaped workload through the public `mod_pow` | dispatch overhead relative to `montpow_rand` (Montgomery ladder for odd moduli) |

Exponentiation cost is (exponent bits) × (kernel cost) and is linear in
exponent length, so every other length follows from these rows: a full-width
2048-bit exponent costs eight times the `montpow_rand` row.

All measurements are single-threaded, against GMP 6.3.0 on every host:

| label | machine | cores | memory | OS |
|---|---|---|---|---|
| **M4** | Apple M4 | 10 | 32 GiB | macOS 26.5.1 |
| **EPYC** | 2 × AMD EPYC 7452 (Zen 2) | 64 (128 threads) | 256 GiB | Ubuntu 24.04.4 LTS |
| **Pi** | Raspberry Pi 5 Model B Rev 1.1 (4 × Cortex-A76) | 4 | 8 GiB | Debian 13 |

GMP numbers come from `pilot_gmp`, a C mirror of `pilot_mp` driven through
the same pilot-bench harness: the same operand distribution, calibration
floor, convergence criterion, and session limits.

## Fitted complexity

Least-squares log–log fit of mean vs bit width, `mean ≈ c·n^α`; the table gives
the **exponent α** only. (The fit's intercept `c` is deliberately not shown: it
carries units of ns/bit^α — *not* nanoseconds — so it is neither a time nor
comparable across rows with different α. Read actual times from the cost tables
below, never α or `c` as a speed.) At 256–4096 bits (4–64 limbs) the exponents
are **sub-asymptotic**: fixed per-call overhead flattens the cheap ops (`add`
reads α≈0.3 though it is O(n)); a higher α means a steeper curve, so `mul`
(α≈1.8) overtakes `add` well before these sizes even though it starts cheaper.
The Euclid family now reads α≈1.0–1.1 — **Lehmer batching** cuts both the
constant and the observed growth against classical Euclid's ≈1.4. `mul`/`sqr`
read α≈1.8 because at these sizes they are mostly schoolbook with a single
Karatsuba split, still below the Toom crossover (~8192 bits). `sqrtmod` and
`isprime` are heavy-tailed: their means are monotone in size but tail-set,
so their fitted exponents move with the sample's composition — read their
extrema (see above).

MD

$PA fit "M4=$M4" "EPYC=$EPYC" "Pi=$PI"

cat <<'MD'

## Cost by method

MD

$PA means "M4=$M4" "EPYC=$EPYC" "Pi=$PI"

cat <<'MD'

EPYC runs ~1.3–1.8× behind the M4 across the board (lower single-thread clock),
and the Pi ~2–5× behind it (a small board core) — the same shapes, shifted up.
The scaling graphs plot all three.

![arithmetic scaling](assets/scaling-arithmetic.svg)

![division scaling](assets/scaling-division.svg)

![montgomery scaling](assets/scaling-montgomery.svg)

![number theory scaling](assets/scaling-number-theory.svg)

## Versus GMP

Each cell is `rump ns / gmp ns / ratio`. Lower ratio is better; **1.0×** would
mean parity. `isprime` is omitted here — its heavy-tailed mean makes the ratio
meaningless (see Extrema). rump's Montgomery domain, `sqrt_mod`, and GF(2^m)
have no `mpz` counterpart and so cannot appear in the comparison; their costs
are in the tables above.

### M4

MD

$PA compare "$M4" bench/gmp_hardy.md | grep -v '`isprime`'

cat <<'MD'

### EPYC

MD

$PA compare "$EPYC" bench/gmp_moore.md | grep -v '`isprime`'

cat <<'MD'

### Pi

MD

$PA compare "$PI" bench/gmp_darby.md | grep -v '`isprime`'

cat <<'MD'

### Interpretation

The comparison sorts rump's primitives into groups, and the grouping is by
**algorithm**, not by language:

- **Competitive — matched algorithm.** `modpow` is 1.1–3.4× off GMP because both
  use windowed Montgomery exponentiation; the gap is constant factors (GMP's
  assembly `mulx`/`adcx` inner loop). `divrem` and `modmul` sit at ~2–4× for the
  same reason. Notably this tightens on the **Pi** (`mul` 1.3–1.9×, `modpow`
  1.1–1.6×): GMP's hand-tuned assembly edge is a wide-core advantage that shrinks
  on the Pi's simpler pipeline, where the pure-Rust penalty is smallest.

- **The Euclid family: Lehmer's algorithm replaced classical Euclid, and
  binary reciprocity replaced the division-per-step Jacobi.** `gcd`,
  `gcd_extended`, and `mod_inverse` ran classical Euclid — one full
  multiprecision division per quotient — and stood 17–89× behind GMP; on
  Lehmer's algorithm they stand 4–13×. `jacobi` performed a full division per
  reduction step and stood 12–29× behind; on binary reciprocity it stands
  2–12×. At 256–4096 bits all four engines are O(n²) while GMP runs
  subquadratic **Half-GCD (HGCD)** under each, so the ratios rise with size on
  the wide M4/EPYC cores. Above ~131 kbit `gcd` dispatches to its own
  Half-GCD (see *GCD at scale* below); `gcd_extended`, `mod_inverse`, and
  `jacobi` pay the quadratic curve at every size. (On the Pi the ratios narrow
  with size instead — from ~10–12× at 256 bits to ~4× at 4096 — as rump's
  fixed per-call overhead amortizes.)

- **`mul`/`sqr` — 1.3–7.5×, widening on the wide cores.** rump climbs
  schoolbook → Karatsuba → **Toom-3 → Toom-4**; Toom-3 crosses in above ~8192
  bits, so at crypto sizes (≤4096 bits) rump is on Karatsuba and the gap is GMP's
  assembly base-case, not the algorithm. GMP escalates to Toom-6.5/8.5 → FFT far
  above rump's range.

- **`add`/`sub` — 2–15×.** Nearly all of this is allocation: rump returns a
  fresh `Vec` per call where GMP's `mpn` layer writes into an existing buffer.
  The absolute difference is tens of nanoseconds per call.

- **Operations with no `mpz` counterpart.** The public Montgomery domain
  (`mul_mont`, `square_mont`, `pow`), `sqrt_mod`, and the GF(2^m) field
  operations cannot appear in this comparison because GMP's integer layer does
  not provide them; their costs are in the tables above.

### Completed and remaining algorithmic work

Completed to date: double-digit Lehmer for the Euclid family (17–89× behind
GMP reduced to 4–13× at 256–4096 bits), the division-free binary Jacobi
(12–29× reduced to 2–12×), Toom-3 and Toom-4 multiplication, Half-GCD behind
`gcd` (subquadratic above ~131 kbit), and Half-GCD behind `gcd_extended` and
`mod_inverse` (above ~32 kbit). The section below measures the results at
scale.

Remaining, in priority order:

1. **Subquadratic `jacobi`.** The scale sweep shows it as the family's only
   remaining quadratic curve: α ≈ 2.0, because its subtract-and-halve steps
   admit no Lehmer batching, with a ratio to GMP of 76× at 256 kbit and 181×
   at 1 Mbit. The algorithm is published: carry the symbol's low-bit state
   through the Half-GCD transform (Brent and Zimmermann, *An O(M(n) log n)
   algorithm for the Jacobi symbol*, ANTS-IX, 2010; GMP's `mpn_jacobi`
   implements the same idea).
2. **In-place `add`/`sub`.** The 2–15× ratios on the cheapest operations are
   allocation: a fresh `Vec` per call against GMP's in-place `mpn` writes.
   The absolute difference is tens of nanoseconds per call, which bounds the
   value of the work.

## GCD at scale

The tables above stop at 4096 bits, where the whole family runs its Lehmer
(or binary) engine. Above that, three of the four functions change algorithm.
`gcd` dispatches to **Half-GCD (HGCD)** past ~131 kbit (2048 limbs): Möller,
*On Schönhage's algorithm and subquadratic integer gcd computation*, Math.
Comp. 77 (2008), 589–607 — the algorithm behind GMP's `mpn_hgcd` — computing
the reduction matrix from the operands' top halves by recursion and replacing
Lehmer's O(n²) with O(M(n)·log n). `gcd_extended` and `mod_inverse` ride the
same driver with the transform accumulated, and their crossover is lower,
~32 kbit (512 limbs), because Lehmer's extended form carries full-width
signed cofactors through every batch while the driver folds that work into
one matrix accumulation per round. This section measures the family from
8 kbit to 1 Mbit on the M4:

- **Three curves bend; one does not.** `gcd`, `gcd_extended`, and
  `mod_inverse` fit visibly shallower exponents than `jacobi`'s α ≈ 2.0 (the
  fit table below), and the fits understate the change: each curve's lower
  range still runs Lehmer, with the subquadratic regime beginning only at
  its dispatch size.
- **The ratios to GMP grow slowly for the Half-GCD functions and quadratically
  for `jacobi`.** Across the sweep, `gcd` runs 4.1× → 12×, `mod_inverse`
  8.3× → 16×, and `gcd_extended` 7.8× → 21×; the residual growth comes from
  the multiplication ladder underneath — GMP's HGCD multiplies by FFT at
  these sizes, rump's by Toom — plus Half-GCD's own constants. `jacobi`,
  still quadratic, runs 30× at 32 kbit, 76× at 256 kbit, and 181× at 1 Mbit.
- **The GMP column states the goal:** α ≈ 1.5 across the whole family,
  achieved by running HGCD beneath every one of these operations. The
  remaining item is `jacobi`.

MD

$PA fit "rump=$GCD_SCALE" "GMP=$GMP_GCD_SCALE"

cat <<'MD'

Each cell below is `rump ns / gmp ns / ratio`, as in the main comparison.

MD

$PA compare "$GCD_SCALE" "$GMP_GCD_SCALE"

cat <<'MD'

![gcd at scale](assets/scaling-gcd-at-scale.svg)

## Extrema — the variable-time signal

Ranked by `max/min` spread (M4). A spread near 1.0 is data-independent; a large
spread means the primitive's cost depends on its input, which is why rump is
explicitly variable-time and must not be used where timing may not leak secrets.

Two operations produce the large spreads:
- **`isprime`** ranges from a ~20 ns small-factor rejection to a full
  twelve-round Miller–Rabin pass on a prime — a spread past **500,000×** at
  2048 bits; the exact figure tracks how many primes the random sample
  contained.
- **`sqrt_mod`** varies with the prime's 2-adic structure — a Blum prime takes
  the `(p+1)/4` shortcut, an NTT-friendly prime the full descent (200–450×).
- Everything else — plain arithmetic, the Montgomery kernels, the Lehmer'd
  Euclid family, GF(2^m) — sits at **1.0–1.6×**: cost tracks operand width, which
  is public, not the operand values.

MD

$PA extrema "M4=$M4" | head -42

cat <<'MD'

The remaining 46 primitives all sit at **1.0–1.2×** — data-independent, their
cost set by operand width alone.

![variable-time scaling](assets/scaling-variable-time.svg)

## Reproduction

```sh
cargo build --release --bin pilot_mp
bash scripts/bench_gmp.sh                      # builds pilot_gmp (needs libgmp)

# rump column, and the GMP column through the same harness, per host:
PILOT_PRESET=normal bash scripts/bench_primitives.sh > bench/primitives_<host>.md
PILOT_MP_BIN=target/bench_gmp/pilot_gmp \
  PILOT_PRESET=normal bash scripts/bench_primitives.sh > bench/gmp_<host>.md

# the GCD-at-scale sweep (8 kbit – 1 Mbit):
bash scripts/bench_gcd_scaling.sh > bench/gcd_scaling_<host>.md
PILOT_MP_BIN=target/bench_gmp/pilot_gmp \
  bash scripts/bench_gcd_scaling.sh > bench/gmp_gcd_scaling_<host>.md

# assemble the whole document (tables, graphs, prose):
bash scripts/build_performance.sh

# or drive the pieces directly:
python3 scripts/perf_analysis.py fit     M4=… EPYC=… Pi=…
python3 scripts/perf_analysis.py means   M4=… EPYC=… Pi=…
python3 scripts/perf_analysis.py compare bench/primitives_<h>.md bench/gmp_<h>.md
python3 scripts/perf_analysis.py extrema M4=…
python3 scripts/perf_analysis.py plot    <family> assets/scaling-<family>.svg M4=… EPYC=… Pi=…
```
MD
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
